---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hugo-static-web.fullname" . }}
  labels:
    {{- include "hugo-static-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.status_port }}
      targetPort: {{ .Values.service.status_port }}
      protocol: TCP
      name: status
  selector:
    {{- include "hugo-static-web.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: 'blog-status'
  labels:
    {{- include "hugo-static-web.labels" . | nindent 4 }}
spec:
  type: 'ClusterIP'
  ports:
    - port: {{ .Values.service.status_port }}
      targetPort: {{ .Values.service.status_port }}
      protocol: TCP
      name: status
  selector:
    {{- include "hugo-static-web.selectorLabels" . | nindent 4 }}