---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsEncrypt.name }}
  # namespace: {{ .Values.namespace }}
spec:
  acme:
    server: {{ .Values.letsEncrypt.server }}
    email: {{ .Values.letsEncrypt.email }}
    privateKeySecretRef:
      name: {{ .Values.letsEncrypt.name }}
    solvers:
    - selector:
        dnsNames:
        - {{ .Values.letsEncrypt.host }}
      dns01:
        route53:
          region: {{ .Values.letsEncrypt.aws.region }}
          hostedZoneID: {{ .Values.letsEncrypt.aws.hosted_zone }}
          accessKeyID: {{ .Values.letsEncrypt.aws.accessKey }}
          secretAccessKeySecretRef:
            name: cert-manager
            key: secretAccessKey
