{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-{{ .Values.app }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.tls.hostname  }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "service-{{ .Values.app }}"
            port: 
              number: {{ .Values.service.port }}
{{- end -}}