---
apiVersion: 'v1'
kind: 'Service'
metadata:
  name: "service-{{ .Values.app }}"
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: 'TCP'
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
